modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Lukarbonite/AutoPickup/issues"
license = "AGPL-3.0-only"

[[mods]]
modId = "autopickup"
version = "${version}"
displayName = "Auto Pickup"
authors = "lukarbonite"
description = '''Auto Pickup mod by lukarbonite'''
logoFile = "autopickup/icon.png"

[[dependencies.autopickup]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autopickup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autopickup]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.autopickup]]
modId = "mixinextras"
mandatory = false
versionRange = "[0.5.3,)"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "autopickup.mixins.json"

[[mixins]]
config = "autopickup.compat.mixins.json"

[[mixins]]
config = "autopickup.forge.mixins.json"