pluginManagement {
    repositories {
        maven { name = 'Fabric';        url = 'https://maven.fabricmc.net/' }
        maven { name = 'Architectury'; url = 'https://maven.architectury.dev/' }
        maven { name = 'NeoForge';     url = 'https://maven.neoforged.net/releases' }
        maven { name = 'Forge';        url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'autopickup'

include ':common'
include ':fabric'
include ':neoforge'
include ':forge'
