modLoader    = "javafml"
loaderVersion = "[4,)"
license       = "AGPL-3.0-only"
issueTrackerURL = "https://github.com/Lukarbonite/AutoPickup/issues"

[[mods]]
    modId       = "autopickup"
    version     = "${version}"
    displayName = "Auto Pickup"
    description = '''Auto Pickup mod by lukarbonite'''
    logoFile    = "assets/autopickup/icon.png"
    authors     = "lukarbonite"

    [[mods.contacts]]
        homepage = "https://github.com/Lukarbonite/AutoPickup"
        sources  = "https://github.com/Lukarbonite/AutoPickup"

[[dependencies."autopickup"]]
    modId        = "neoforge"
    type         = "required"
    versionRange = "[21.0.0-beta,21.2.0-beta)"
    ordering     = "NONE"
    side         = "BOTH"

[[dependencies."autopickup"]]
    modId        = "minecraft"
    type         = "required"
    versionRange = "[1.21,1.21.2)"
    ordering     = "NONE"
    side         = "BOTH"

[[mixins]]
    config = "autopickup.mixins.json"

[[mixins]]
    config = "autopickup.compat.mixins.json"

[[mixins]]
    config = "autopickup.neoforge.mixins.json"
